name: renting_assistant
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.6
  azlistview: ^0.1.1
  lpinyin: ^1.0.7
  shared_preferences: ^0.5.2
  fluttertoast: ^3.0.4
  dio: ^2.1.3
  flutter_spinkit: ^3.1.0
  flutter_staggered_grid_view: ^0.2.7
  amap_base: ^0.3.5
  webview_flutter: ^0.3.7+1
  event_bus: ^1.1.0
  jpush_flutter: ^0.0.11
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/web/house_info_map.html
    - assets/data/china.json
    - assets/data/region.json
    - assets/images/aircondition.png
    - assets/images/bed.png
    - assets/images/gas.png
    - assets/images/heater.png
    - assets/images/heating.png
    - assets/images/internet.png
    - assets/images/refrigerator.png
    - assets/images/tv.png
    - assets/images/wardrobe.png
    - assets/images/washer.png
    - assets/images/bg.png
    - assets/images/q&a_1.png
    - assets/images/q&a_2.png
    - assets/images/q&a_3.png
    - assets/images/q&a_4.png
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/font/iconfont.ttf
